# Generated by Django 4.0.3 on 2022-05-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_employee_office_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentEmployeeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('office_place', models.CharField(default='ds', max_length=50)),
                ('department_name', models.CharField(max_length=50)),
            ],
        ),
    ]
