# Generated by Django 4.0.3 on 2022-05-19 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_departmentemployeetable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmentemployeetable',
            old_name='department_name',
            new_name='name',
        ),
    ]
