# Generated by Django 4.0.3 on 2022-05-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_department_name_departmentemployeetable_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='office_place',
            new_name='office_place1',
        ),
        migrations.AddField(
            model_name='departmentemployeetable',
            name='office_place1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='department',
            name='office_place',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='departmentemployeetable',
            name='office_place',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
