# Generated by Django 4.0.3 on 2022-05-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_office_place_employee_office_place1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentemployeetable',
            name='office_place',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='departmentemployeetable',
            name='office_place1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='office_place1',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
