# Generated by Django 4.0.3 on 2022-05-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_faculty_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='office_place1',
            field=models.CharField(blank=True, default='None', max_length=50),
        ),
    ]
